# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a8e76d571738ddeefc13467dd4b943cdca1376dd0f6ff56919fa9583236c5ed62e3681c099d064e80e059f5727d5d2b9019c71f7007c7525ecb4c460b4309ce

test:
  secret_key_base: 05948a2174dc316566a600b6c34165b4713be618370375cb2589c7312f25cb4b9eb7a5340e964c2d924381a657042d525330d629bb4b10593a2f676b27556c6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
